# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-26 02:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, null=True)),
                ('url', models.URLField(db_index=True, max_length=128, null=True)),
            ],
        ),
    ]
