# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-06 18:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, null=True)),
                ('image', models.FileField(upload_to='events_images/')),
                ('brief', models.CharField(max_length=500, null=True)),
                ('url', models.URLField(db_index=True, max_length=128, null=True)),
                ('date', models.DateField()),
                ('typeofentry', models.CharField(choices=[('past', 'Past Event'), ('upcoming', 'Upcoming Event'), ('suggested', 'Suggested Event')], default='suggestion', max_length=20)),
                ('suggested_by', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'permissions': (('approve_suggestion', 'Approve a suggested event'),),
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, null=True)),
                ('url', models.URLField(db_index=True, max_length=128, null=True)),
            ],
        ),
    ]
