# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-06 21:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='typeofentry',
            field=models.CharField(choices=[('past', 'Past Event'), ('upcoming', 'Upcoming Event'), ('suggested', 'Suggested Event')], default='suggested', max_length=20),
        ),
    ]
