# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-21 07:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_resourceurl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='url',
        ),
    ]
