# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-30 11:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_resource_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourceurl',
            name='category',
            field=models.CharField(choices=[('video', 'Videos'), ('blog', 'Blogs / Articles'), ('ebook', 'E-Books'), ('other', 'Others')], max_length=128, null=True),
        ),
    ]
