# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-28 17:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_events_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='image',
            field=models.FileField(upload_to='events_images/'),
        ),
    ]
