# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-01 09:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20180428_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='events',
            name='typeofentry',
            field=models.CharField(default='Suggestion', max_length=20),
        ),
    ]
