# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-07 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20180507_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.FileField(upload_to='events_images/'),
        ),
    ]
