# Generated by Django 2.1 on 2018-08-15 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_resourceurl_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='resourceurl',
            name='resource',
        ),
        migrations.AddField(
            model_name='resource',
            name='category',
            field=models.CharField(choices=[('video', 'Videos'), ('blog', 'Blogs / Articles'), ('ebook', 'E-Books'), ('other', 'Others')], max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='description',
            field=models.CharField(blank=True, max_length=10240, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='url',
            field=models.URLField(db_index=True, max_length=128, null=True),
        ),
        migrations.DeleteModel(
            name='ResourceURL',
        ),
        migrations.AddField(
            model_name='resource',
            name='resource',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.Topic'),
            preserve_default=False,
        ),
    ]
