# Generated by Django 2.1 on 2018-08-16 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20180815_0959'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resource',
            old_name='resource',
            new_name='topic',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='description',
        ),
    ]
