# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-01 10:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20180501_0909'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='suggested_by',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
