# Generated by Django 2.1 on 2018-08-16 09:40

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20180816_0920'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='description',
            field=tinymce.models.HTMLField(default='sdf'),
            preserve_default=False,
        ),
    ]
