# Generated by Django 2.1 on 2018-08-16 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_resource_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='url',
            field=models.URLField(blank=True, db_index=True, max_length=128, null=True),
        ),
    ]
