# Generated by Django 2.1 on 2018-10-01 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20181001_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='github_handle',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
