# Generated by Django 2.1 on 2018-10-01 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20181001_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='branch',
            field=models.CharField(choices=[('', 'Choose Branch'), ('CSE', 'CSE'), ('IT', 'IT'), ('ECE', 'ECE'), ('EEE', 'EEE'), ('Mech', 'Mech'), ('Bio Tech', 'Bio Tech')], max_length=100),
        ),
        migrations.AlterField(
            model_name='users',
            name='year',
            field=models.CharField(choices=[('', 'Choose Year'), ('I', 'I'), ('II', 'II'), ('III', 'III'), ('IV', 'IV')], max_length=10),
        ),
    ]
